# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"sigmoid": "kernel.ipynb",
         "make_bimodal_assymetric_regression": "kernel.ipynb",
         "sparsify": "utils.ipynb",
         "hstack": "utils.ipynb",
         "vstack": "utils.ipynb",
         "stack": "utils.ipynb",
         "RobustEncoder": "utils.ipynb",
         "PrefitEstimator": "kernel.ipynb",
         "BaseMixedForest": "kernel.ipynb",
         "HeterogeneousMixedForest": "kernel.ipynb",
         "MixedForestRegressor": "kernel.ipynb",
         "MixedForestClassifier": "kernel.ipynb",
         "ForestBipartiteGraphTransformer": "kernel.ipynb",
         "EstimatorKernel": "kernel.ipynb",
         "JaccardForestKernel": "kernel.ipynb",
         "CategoricalLinearKernel": "kernel.ipynb",
         "ClassificationLinearBottleneck": "kernel.ipynb",
         "RegressionLinearBottleneck": "kernel.ipynb",
         "MLPKernel": "kernel.ipynb",
         "BOWKernel": "kernel.ipynb",
         "DiscretizedTargetKernel": "kernel.ipynb",
         "get_default_args": "utils.ipynb",
         "inherit_docstrings": "utils.ipynb",
         "make_batches": "utils.ipynb",
         "sim_matrix_to_idx_and_score": "utils.ipynb",
         "cosine_similarity": "utils.ipynb",
         "cosine_distance": "utils.ipynb",
         "sparse_dot_product": "utils.ipynb",
         "similarity_plot": "utils.ipynb"}

modules = ["kernel.py",
           "utils.py"]

doc_url = "https://AlanGanem.github.io/heartwood/"

git_url = "https://github.com/AlanGanem/heartwood/tree/master/"

def custom_doc_links(name): return None
